# ansible-playbook -i ~/ansible/hosts /playbooks/new-default.yml
---
- hosts: newuser
  gather_facts: yes
  #transport: paramiko
  vars:
    wifi_country: "US"
    locale: "en_US.UTF-8"
    keyboard: "pc104"
    keyboard_layout: "us"
    timezone: America/Los_Angeles
    locale_options:
    # Disable Default (GB) Locale
    - regexp: "^#?en_GB.UTF-8 UTF-8"
      line: "# en_GB.UTF-8 UTF-8"
    # Enable US Locale
    - regexp: "^#?en_US.UTF-8 UTF-8"
      line: "en_US.UTF-8 UTF-8"
    hostname: blackberrypi

  tasks:
  # ~~~~~~~~~~~~~~~~~ Expand filesystem ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - name: Expand filesystem to fill disk
    command: raspi-config --expand-rootfs
    become: yes
    notify:
      - reboot
    tags: expand

  # ~~~~~~~~~~~~~~~~~ Locale and Internationalization~~~~~~~~~~~~~~~~~~~~~
  # Configure /etc/locale.gen values
  - name: Configure option values in /etc/locale.gen file.
    become: yes
    lineinfile:
      dest: /etc/locale.gen
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: EOF
      state: present
    with_items: "{{ locale_options }}"
    tags: initial

  # Generate Locale
  - name: Generate Locale
    become: yes
    command: locale-gen {{ locale }}
    tags: initial

  # Set Locale
  - name: Set Locale
    become: yes
    command: update-locale LC_ALL={{ locale }} LANG={{ locale }}
    tags: initial

  # set /etc/timezone
  - name: set /etc/timezone
    become: yes
    command: timedatectl set-timezone {{ timezone }}
    tags: initial

  # set /etc/default/keyboard
  - name: set /etc/default/keyboard
    become: yes
    template: src=roles/common/templates/keyboard dest=/etc/default/keyboard
    notify: reboot
    tags: initial

    # Set the hostname
  - name: Set the hostname
    become: yes
    command: hostnamectl set-hostname "{{ hostname }}"
    notify: reboot
    tags: hostname

  - name: Place new /etc/hosts file
    become: yes
    template:
      src: roles/common/templates/hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
    notify: reboot


  handlers:
  #~~~~~~~~~~~~~~~ reboot ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - name: reboot
    command: shutdown -r +0 'Ansible Reboot triggered'
    async: 0
    poll: 0
    ignore_errors: true
    become: true
